export { default as HomeLayout } from "./HomeLayout";
export { default as Commercial } from "./Commercial";
export { default as Contact } from "./Contact";
export { default as Work } from "./Work";
export { default as ShowReel } from "./ShowReel";
export { default as ShortFilm } from "./ShortFilm";
export { default as FashionFilm } from "./FashionFilm";
export { default as MusicVideo } from "./MusicVideo";
export { default as ProjectDetails } from "./ProjectDetails";