import { nanoid } from "nanoid";
import placeholder from "./assets/placeholderOne.jpg";
// import video from "./assets/video.mp4";

export const navLinks = [
  // { id: nanoid(), href: "/work", text: "work" },
  { id: nanoid(), path: "/music-video", text: "music video" },
  { id: nanoid(), path: "/commercial", text: "commercial" },
  { id: nanoid(), path: "/short-film", text: "shortfilm" },
  { id: nanoid(), path: "/fashion-film", text: "fashion film" },
  { id: nanoid(), path: "/show-reel", text: "showreel" },
  { id: nanoid(), path: "/contact", text: "contact" },
];

export const projects = [
  {
    id: nanoid(),
    img: placeholder,
    title: "aron • especial",
    service: "music video",
    video: "https://www.youtube.com/embed/syHSnmPaBaE",
    projectInformation: {
      title: "Cinematic Short – The Golden Hour",
      clientName: "Worked with XYZ Productions",
      directorDPName: "Shot by John Doe",
      beforeAfterLabel: "Before | After",
    },
    yourRole: {
      colorGradingStyle: "Warm Cinematic Look with Teal & Orange",
      softwareUsed: "Graded in DaVinci Resolve",
      specialTechniques: ["HDR Workflow", "Film Emulation", "LUTs"],
    },
    callToAction: {
      contactDetails: "Available for freelance work. Contact: your@email.com",
      socialMediaLinks: "Follow @yourhandle on Instagram",
    },
    gallery: {
      img1: placeholder,
      img2: placeholder,
      img3: placeholder,
      img4: placeholder,
      img5: placeholder,
      img6: placeholder,
      img7: placeholder,
      img8: placeholder,
      img9: placeholder,
      img10: placeholder,
    },
  },
  {
    id: nanoid(),
    img: placeholder,
    title: "leo • prime",
    service: "music video",
    video: "https://www.youtube.com/embed/syHSnmPaBaE",
    projectInformation: {
      title: "Cinematic Short – The Golden Hour",
      clientName: "Worked with XYZ Productions",
      directorDPName: "Shot by John Doe",
      beforeAfterLabel: "Before | After",
    },
    yourRole: {
      colorGradingStyle: "Warm Cinematic Look with Teal & Orange",
      softwareUsed: "Graded in DaVinci Resolve",
      specialTechniques: ["HDR Workflow", "Film Emulation", "LUTs"],
    },
    callToAction: {
      contactDetails: "Available for freelance work. Contact: your@email.com",
      socialMediaLinks: "Follow @yourhandle on Instagram",
    },
    gallery: {
      img1: placeholder,
      img2: placeholder,
      img3: placeholder,
      img4: placeholder,
      img5: placeholder,
      img6: placeholder,
      img7: placeholder,
      img8: placeholder,
      img9: placeholder,
      img10: placeholder,
    },
  },
  {
    id: nanoid(),
    img: placeholder,
    title: "nova • stellar",
    service: "music video",
    video: "https://www.youtube.com/embed/syHSnmPaBaE",
    projectInformation: {
      title: "Cinematic Short – The Golden Hour",
      clientName: "Worked with XYZ Productions",
      directorDPName: "Shot by John Doe",
      beforeAfterLabel: "Before | After",
    },
    yourRole: {
      colorGradingStyle: "Warm Cinematic Look with Teal & Orange",
      softwareUsed: "Graded in DaVinci Resolve",
      specialTechniques: ["HDR Workflow", "Film Emulation", "LUTs"],
    },
    callToAction: {
      contactDetails: "Available for freelance work. Contact: your@email.com",
      socialMediaLinks: "Follow @yourhandle on Instagram",
    },
    gallery: {
      img1: placeholder,
      img2: placeholder,
      img3: placeholder,
      img4: placeholder,
      img5: placeholder,
      img6: placeholder,
      img7: placeholder,
      img8: placeholder,
      img9: placeholder,
      img10: placeholder,
    },
  },
  {
    id: nanoid(),
    img: placeholder,
    title: "mira • elite",
    service: "music video",
    video: "https://www.youtube.com/embed/syHSnmPaBaE",
    projectInformation: {
      title: "Cinematic Short – The Golden Hour",
      clientName: "Worked with XYZ Productions",
      directorDPName: "Shot by John Doe",
      beforeAfterLabel: "Before | After",
    },
    yourRole: {
      colorGradingStyle: "Warm Cinematic Look with Teal & Orange",
      softwareUsed: "Graded in DaVinci Resolve",
      specialTechniques: ["HDR Workflow", "Film Emulation", "LUTs"],
    },
    callToAction: {
      contactDetails: "Available for freelance work. Contact: your@email.com",
      socialMediaLinks: "Follow @yourhandle on Instagram",
    },
    gallery: {
      img1: placeholder,
      img2: placeholder,
      img3: placeholder,
      img4: placeholder,
      img5: placeholder,
      img6: placeholder,
      img7: placeholder,
      img8: placeholder,
      img9: placeholder,
      img10: placeholder,
    },
  },
  {
    id: nanoid(),
    img: placeholder,
    title: "zayn • supreme",
    service: "music video",
    video: "https://www.youtube.com/embed/syHSnmPaBaE",
    projectInformation: {
      title: "Cinematic Short – The Golden Hour",
      clientName: "Worked with XYZ Productions",
      directorDPName: "Shot by John Doe",
      beforeAfterLabel: "Before | After",
    },
    yourRole: {
      colorGradingStyle: "Warm Cinematic Look with Teal & Orange",
      softwareUsed: "Graded in DaVinci Resolve",
      specialTechniques: ["HDR Workflow", "Film Emulation", "LUTs"],
    },
    callToAction: {
      contactDetails: "Available for freelance work. Contact: your@email.com",
      socialMediaLinks: "Follow @yourhandle on Instagram",
    },
    gallery: {
      img1: placeholder,
      img2: placeholder,
      img3: placeholder,
      img4: placeholder,
      img5: placeholder,
      img6: placeholder,
      img7: placeholder,
      img8: placeholder,
      img9: placeholder,
      img10: placeholder,
    },
  },
  {
    id: nanoid(),
    img: placeholder,
    title: "kai • aurora",
    service: "music video",
    video: "https://www.youtube.com/embed/syHSnmPaBaE",
    projectInformation: {
      title: "Cinematic Short – The Golden Hour",
      clientName: "Worked with XYZ Productions",
      directorDPName: "Shot by John Doe",
      beforeAfterLabel: "Before | After",
    },
    yourRole: {
      colorGradingStyle: "Warm Cinematic Look with Teal & Orange",
      softwareUsed: "Graded in DaVinci Resolve",
      specialTechniques: ["HDR Workflow", "Film Emulation", "LUTs"],
    },
    callToAction: {
      contactDetails: "Available for freelance work. Contact: your@email.com",
      socialMediaLinks: "Follow @yourhandle on Instagram",
    },
    gallery: {
      img1: placeholder,
      img2: placeholder,
      img3: placeholder,
      img4: placeholder,
      img5: placeholder,
      img6: placeholder,
      img7: placeholder,
      img8: placeholder,
      img9: placeholder,
      img10: placeholder,
    },
  },
  {
    id: nanoid(),
    img: placeholder,
    title: "sage • genesis",
    service: "music video",
    video: "https://www.youtube.com/embed/syHSnmPaBaE",
    projectInformation: {
      title: "Cinematic Short – The Golden Hour",
      clientName: "Worked with XYZ Productions",
      directorDPName: "Shot by John Doe",
      beforeAfterLabel: "Before | After",
    },
    yourRole: {
      colorGradingStyle: "Warm Cinematic Look with Teal & Orange",
      softwareUsed: "Graded in DaVinci Resolve",
      specialTechniques: ["HDR Workflow", "Film Emulation", "LUTs"],
    },
    callToAction: {
      contactDetails: "Available for freelance work. Contact: your@email.com",
      socialMediaLinks: "Follow @yourhandle on Instagram",
    },
    gallery: {
      img1: placeholder,
      img2: placeholder,
      img3: placeholder,
      img4: placeholder,
      img5: placeholder,
      img6: placeholder,
      img7: placeholder,
      img8: placeholder,
      img9: placeholder,
      img10: placeholder,
    },
  },
  {
    id: nanoid(),
    img: placeholder,
    title: "ryu • ascend",
    service: "music video",
    video: "https://www.youtube.com/embed/syHSnmPaBaE",
    projectInformation: {
      title: "Cinematic Short – The Golden Hour",
      clientName: "Worked with XYZ Productions",
      directorDPName: "Shot by John Doe",
      beforeAfterLabel: "Before | After",
    },
    yourRole: {
      colorGradingStyle: "Warm Cinematic Look with Teal & Orange",
      softwareUsed: "Graded in DaVinci Resolve",
      specialTechniques: ["HDR Workflow", "Film Emulation", "LUTs"],
    },
    callToAction: {
      contactDetails: "Available for freelance work. Contact: your@email.com",
      socialMediaLinks: "Follow @yourhandle on Instagram",
    },
    gallery: {
      img1: placeholder,
      img2: placeholder,
      img3: placeholder,
      img4: placeholder,
      img5: placeholder,
      img6: placeholder,
      img7: placeholder,
      img8: placeholder,
      img9: placeholder,
      img10: placeholder,
    },
  },
];
